name: Deploy Website

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          
      - name: Install dependencies
        run: npm install
        
      - name: Run Cypress Tests
        uses: actions/github-script@v6
        with:
          script: |
            const { execSync } = require('child_process');
            try {
              execSync('npm run api_dev', { stdio: 'inherit' });
            } catch (error) {
              console.error('Cypress tests failed.');
              process.exit(1);
            }

      - name: Deploy to GitHub Pages
        if: success() # Only deploy if tests pass
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PAT }}
          publish_dir: ./public